# plugins:
#   - serverless-plugin-monorepo

goatsApp:
  component: serverless-next.js
  # https://github.com/danielcondemarin/serverless-next.js#inputs
  inputs:
    bucketName: fivehundredgoats
    build:
      cwd: ./app/
    # domain: ['fivehundredgoats.club']
    name: fivehundredgoats
    nextConfigDir: ./app/
    # By default the Lambda@Edge functions run using AWSLambdaBasicExecutionRole
    # which only allows uploading logs to CloudWatch. If you need permissions
    # beyond this, like for example access to DynamoDB or any other AWS resource
    # you will need your own custom policy arn:
    # policy: 'arn:aws:iam::123456789012:policy/MyCustomPolicy'
